version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - PORT=50051
    command: python server.py

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      - HOST=server
      - PORT=50051
    command: python client.py
